# Generated by Django 4.1.3 on 2022-11-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=254, null=True)),
                ('distance', models.TextField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
