# Generated by Django 4.1.3 on 2022-12-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0003_puzzlegame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlegame',
            name='timer',
            field=models.IntegerField(default=30, max_length=5),
        ),
    ]
