# Generated by Django 3.1.7 on 2021-05-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='app_exe',
            field=models.FileField(upload_to='main/exe'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='app_py',
            field=models.FileField(upload_to='main/python'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='developer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='icon',
            field=models.ImageField(upload_to='main/icons'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
