# Generated by Django 3.1.7 on 2021-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210523_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
