# Generated by Django 3.1.7 on 2021-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_appmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
