# Generated by Django 3.1.7 on 2021-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210523_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='slug',
            field=models.SlugField(default='default', unique=True),
        ),
    ]
