# Generated by Django 3.1.7 on 2021-06-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_userregistrationmodel_date_of_birth'),
        ('apps', '0007_auto_20210527_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('screenshots', models.ImageField(null=True, upload_to='issues')),
            ],
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='app_exe',
            field=models.FileField(upload_to='exe'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='app_py',
            field=models.FileField(upload_to='python'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='icon',
            field=models.ImageField(upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='screenshots',
            field=models.ImageField(null=True, upload_to='screenshots'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, max_length=10.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.userregistrationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.appmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.userregistrationmodel')),
            ],
        ),
    ]
