# Generated by Django 3.1.7 on 2021-06-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20210609_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.appmodel')),
            ],
        ),
    ]
