# Generated by Django 3.1.7 on 2021-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_appstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstats',
            name='download_size_py',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstats',
            name='download_size_windows',
            field=models.IntegerField(default=0),
        ),
    ]
