# Generated by Django 3.1.7 on 2021-07-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20210614_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots')),
            ],
        ),
        migrations.RemoveField(
            model_name='appmodel',
            name='screenshots',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='screenshots',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AddField(
            model_name='screenshots',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.appmodel'),
        ),
    ]
