# Generated by Django 3.1.7 on 2022-01-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20210710_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='screenshots'),
        ),
        migrations.DeleteModel(
            name='Screenshots',
        ),
    ]
