# Generated by Django 3.1.7 on 2022-01-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20220105_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='image',
            field=models.FileField(upload_to='screenshots'),
        ),
    ]
