# Generated by Django 3.1.7 on 2022-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20220105_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='appmodel',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='screenshot'),
        ),
    ]
