# Generated by Django 3.1.7 on 2022-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
