# Generated by Django 3.1.7 on 2022-07-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20220710_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.appmodel'),
        ),
    ]
