# Generated by Django 3.1.7 on 2022-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_rating_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
