# Generated by Django 4.1.3 on 2022-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20220923_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
