# Generated by Django 4.1.3 on 2022-11-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_alter_appmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppStats',
        ),
    ]
